<?php
/**
* Implements hook_menu()
* Test
*/
function ychenik_form_menu() {
  $items = array();
  $items['examples/form'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Example Form', //page title
    'description' => 'A form to mess around with.',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('ychenik_form_form'), //put the name of the form here
    'access callback' => TRUE
  );
  return $items;
}
//****************
/**
* Implements hook_form()
* Test
*/
function ychenik_form_form($node, &$form_state) {
  $form = array();
    $form['name'] = array(
      '#type'          => 'textfield',
      '#title'         => t('Name'),
      '#required'      => FALSE,
      '#description'   => t('Your Last name goes here'),    
    );
    $form['telephone'] = array(
      '#type'          => 'textfield',
      '#title'         => t('Phone Number'),
      '#description'   => "Please enter your phone number.",
      '#size'          => 15,
    );
    $form['country'] = array(
      '#type'          =>'select',
      '#title'         =>t('Select your country'),
      '#options'       =>array('USA','UK','France','Japan'),
    );

    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Submit'),
    );
    return $form;
}
//****************
/**
* Implements hook_submit()
* Test
*/ 
function ychenik_form_form_submit($form, &$form_state) {
  $name = $form_state['values']['name'];
  $phone = $form_state['values']['telephone'];
//  drupal_goto("my_view/".$name."/".$phone); //Here are arguments from form into URL
  drupal_set_message(t( "$name "."$phone ".'Your form has been submitted successfully.'));
//  $form_state['redirect'] = array('node/68');
//  $form_state['rebuild'] = TRUE;" //in the submit function so that Drupal does not clear the form.
}

